-- AlterTable
ALTER TABLE "Stream" ALTER COLUMN "url" DROP DEFAULT,
ALTER COLUMN "duration" DROP DEFAULT,
ALTER COLUMN "thumbnailUrlHQ" DROP DEFAULT,
ALTER COLUMN "thumbnailUrlLQ" DROP DEFAULT,
ALTER COLUMN "title" DROP DEFAULT;
